export const MOCK_PRODUCTS = [
  { id:1,  name:'Apple MacBook Pro 14" M3 Pro 18GB 512GB', category:'Bilgisayar', price:62999, originalPrice:69999, rating:4.8, reviewCount:234,  freeShipping:true,  badge:null,            brand:'Apple',    stockQuantity:15, description:'Apple M3 Pro çip, 18GB birleşik bellek, 512GB SSD depolama. ProMotion teknolojisi ile 120Hz yenileme hızı. 18 saate kadar pil ömrü.' },
  { id:2,  name:'Samsung Galaxy Tab S9 FE 10.9" 128GB Wi-Fi', category:'Tablet',      price:8399,  originalPrice:10999, rating:4.5, reviewCount:1120, freeShipping:true,  badge:'FIRSATLAR',     brand:'Samsung',  stockQuantity:42, description:'10.9" TFT ekran, Samsung Exynos 1380 işlemci, 6GB RAM, 128GB depolama, Wi-Fi 6 desteği.' },
  { id:3,  name:'Lenovo IdeaPad Gaming 3 Ryzen 5 16GB 512GB RTX 3050', category:'Bilgisayar', price:28499, originalPrice:31999, rating:4.6, reviewCount:567, freeShipping:true, badge:null, brand:'Lenovo', stockQuantity:8, description:'AMD Ryzen 5 7535HS, 16GB DDR5 RAM, 512GB NVMe SSD, NVIDIA GeForce RTX 3050, 15.6" FHD 144Hz ekran.' },
  { id:4,  name:'Samsung 65" Neo QLED 4K Smart TV', category:'Elektronik',  price:34999, originalPrice:44999, rating:4.7, reviewCount:89,   freeShipping:true,  badge:'ÇOK AL AZ ÖDE', brand:'Samsung',  stockQuantity:5,  description:'Neo QLED 4K, Quantum HDR, Object Tracking Sound+, Smart TV Tizen OS 7.0.' },
  { id:5,  name:'iPhone 15 Pro Max 256GB Doğal Titanyum', category:'Telefon',     price:74999, originalPrice:79999, rating:4.9, reviewCount:2341, freeShipping:true,  badge:null,            brand:'Apple',    stockQuantity:20, description:'A17 Pro çip, titanyum tasarım, 48MP ana kamera, Action Button, USB-C bağlantısı.' },
  { id:6,  name:'Xiaomi Redmi Pad Pro 8GB 256GB 12.1"', category:'Tablet',      price:7249,  originalPrice:8399,  rating:4.4, reviewCount:334,  freeShipping:true,  badge:'KUPONLU ÜRÜN',  brand:'Xiaomi',   stockQuantity:55, description:'Snapdragon 7s Gen 2, 12.1" 2.5K ekran, 10000mAh batarya, 45W hızlı şarj.' },
  { id:7,  name:'ASUS ROG Strix G16 Intel i9 32GB 1TB RTX 4080', category:'Bilgisayar', price:89999, originalPrice:99999, rating:4.8, reviewCount:156, freeShipping:true, badge:null, brand:'ASUS', stockQuantity:3, description:'Intel Core i9-14900HX, 32GB DDR5, 1TB PCIe 4.0 SSD, RTX 4080 12GB, 16" QHD+ 240Hz.' },
  { id:8,  name:'Sony WH-1000XM5 Kablosuz Kulaklık', category:'Elektronik',  price:9499,  originalPrice:12999, rating:4.9, reviewCount:4523, freeShipping:true,  badge:'ÜCRETSİZ KARGO', brand:'Sony',     stockQuantity:30, description:'Sektör lideri gürültü engelleme, 30 saate kadar pil ömrü, Multipoint bağlantı.' },
  { id:9,  name:'Huawei MateBook D16 Intel i5 16GB 512GB', category:'Bilgisayar', price:21999, originalPrice:24999, rating:4.3, reviewCount:211, freeShipping:false, badge:null, brand:'Huawei', stockQuantity:12, description:'Intel Core i5-12450H, 16GB DDR4, 512GB NVMe SSD, 16" FHD IPS matris ekran.' },
  { id:10, name:'Apple iPad Air 11" M2 256GB Wi-Fi Mor', category:'Tablet',      price:24999, originalPrice:27999, rating:4.7, reviewCount:678,  freeShipping:true,  badge:null,            brand:'Apple',    stockQuantity:18, description:'Apple M2 çip, 11" Liquid Retina ekran, USB-C, 5G desteği (isteğe bağlı), iPadOS 17.' },
  { id:11, name:'Logitech MX Master 3S Kablosuz Mouse', category:'Elektronik',  price:2799,  originalPrice:3499,  rating:4.8, reviewCount:1890, freeShipping:true,  badge:'ÜCRETSİZ KARGO', brand:'Logitech', stockQuantity:100, description:'8000 DPI sensör, ses yalıtımlı tıklama, MagSpeed tekerlek, 70 gün pil ömrü.' },
  { id:12, name:'Samsung 27" Odyssey G5 165Hz QHD Curved', category:'Elektronik',  price:8999,  originalPrice:11999, rating:4.6, reviewCount:445,  freeShipping:true,  badge:null,            brand:'Samsung',  stockQuantity:22, description:'1ms GTG, FreeSync Premium, HDR10, 1000R eğri ekran, HDMI 2.0 x2.' },
  { id:13, name:'MSI Prestige 14 Evo Intel i7 16GB 512GB', category:'Bilgisayar', price:25999, originalPrice:28999, rating:4.5, reviewCount:132, freeShipping:true, badge:null, brand:'MSI', stockQuantity:7, description:'Intel Core Ultra 7 155H, Intel Arc grafik, 16GB LPDDR5, 1TB NVMe SSD, 14" 2.8K OLED.' },
  { id:14, name:'Xiaomi 14 Ultra 512GB Siyah', category:'Telefon',     price:49999, originalPrice:54999, rating:4.7, reviewCount:891,  freeShipping:true,  badge:'HIZLI KARGO',   brand:'Xiaomi',   stockQuantity:14, description:'Snapdragon 8 Gen 3, Leica quad kamera, 5000mAh, 90W kablolu + 80W kablosuz şarj.' },
  { id:15, name:'TP-Link Archer AX73 Wi-Fi 6 Router', category:'Elektronik',  price:2199,  originalPrice:2899,  rating:4.5, reviewCount:567,  freeShipping:true,  badge:null,            brand:'TP-Link',  stockQuantity:45, description:'AX5400, Wi-Fi 6, 6 anten, OneMesh, 1.5GHz üçlü çekirdek işlemci.' },
  { id:16, name:'AMD Ryzen 9 7950X 4.5GHz 16 Çekirdek', category:'Bilgisayar', price:15249, originalPrice:17999, rating:4.9, reviewCount:203, freeShipping:false, badge:null, brand:'AMD', stockQuantity:9, description:'AM5 soket, 16 çekirdek / 32 iş parçacığı, 80MB toplam önbellek, 170W TDP.' },
  { id:17, name:'Mavi Erkek Slim Fit Jean Pantolon', category:'Moda',        price:899,   originalPrice:1199,  rating:4.4, reviewCount:2341, freeShipping:true,  badge:'ÜCRETSİZ KARGO', brand:'Mavi',     stockQuantity:200, description:'%98 pamuk, %2 elastan. Slim fit kesim, orta bel. 5 cep modeli.' },
  { id:18, name:'Nike Air Max 270 Erkek Spor Ayakkabı', category:'Moda',        price:3499,  originalPrice:4299,  rating:4.6, reviewCount:1123, freeShipping:true,  badge:null,            brand:'Nike',     stockQuantity:60, description:'Max Air yastıklama, nefes alabilir örgü üst, dayanıklı lastik taban.' },
  { id:19, name:'IKEA MALM Çift Karyola 160x200', category:'Ev & Yaşam', price:4599,  originalPrice:5299,  rating:4.3, reviewCount:445,  freeShipping:false, badge:null,            brand:'IKEA',     stockQuantity:11, description:'Boyalı astarlı yüzey, kaplama, yüksek karyola yatağı için uygun. 160x200 cm.' },
  { id:20, name:'Tefal Ingenio Preference 13 Parça Tencere Seti', category:'Ev & Yaşam', price:2849, originalPrice:3999, rating:4.7, reviewCount:2109, freeShipping:true, badge:'FIRSATLAR', brand:'Tefal', stockQuantity:33, description:'Çıkarılabilir sap teknolojisi, titanyum kaplama, indüksiyonlu ocak uyumlu.' },
  { id:21, name:'Sapiens – Yuval Noah Harari (Türkçe)', category:'Kitap & Müzik', price:189, originalPrice:249, rating:4.9, reviewCount:8901, freeShipping:true, badge:null, brand:'Kolektif Kitap', stockQuantity:500, description:'İnsanlığın kısa tarihi. Dünyada en çok satan kitaplardan biri. 624 sayfa, ciltsiz.' },
  { id:22, name:'Adidas Tiro 23 Erkek Antrenman Şortu', category:'Spor',        price:649,   originalPrice:899,   rating:4.5, reviewCount:678,  freeShipping:true,  badge:'ÜCRETSİZ KARGO', brand:'Adidas',   stockQuantity:150, description:'Hafif dokuma kumaş, AEROREADY nem yönetimi, elastik bel bandı.' },
  { id:23, name:'Philips Airfryer XL 6.2L Yağsız Fritöz', category:'Ev & Yaşam', price:4299, originalPrice:5499, rating:4.8, reviewCount:3211, freeShipping:true, badge:'ÇOK AL AZ ÖDE', brand:'Philips', stockQuantity:28, description:'6.2L XL hacim, RapidAir teknolojisi, dijital dokunmatik ekran, 7 program.' },
  { id:24, name:'HP LaserJet MFP M234dw Kablosuz Yazıcı', category:'Elektronik',  price:5499,  originalPrice:6799,  rating:4.4, reviewCount:334,  freeShipping:true,  badge:null,            brand:'HP',       stockQuantity:17, description:'Çift taraflı baskı, Wi-Fi+Bluetooth, 30 s/dk baskı hızı, HP Smart uygulaması.' },
];

export const MOCK_CATEGORIES = ['Elektronik','Bilgisayar','Tablet','Telefon','Moda','Ev & Yaşam','Spor','Kitap & Müzik'];

export const CATEGORY_META = [
  { id:'Elektronik',    icon:'⚡', color:'#2563eb' },
  { id:'Bilgisayar',    icon:'💻', color:'#7c3aed' },
  { id:'Tablet',        icon:'📱', color:'#0891b2' },
  { id:'Telefon',       icon:'📞', color:'#dc2626' },
  { id:'Moda',          icon:'👗', color:'#e91e8c' },
  { id:'Ev & Yaşam',    icon:'🏠', color:'#16a34a' },
  { id:'Spor',          icon:'⚽', color:'#d97706' },
  { id:'Kitap & Müzik', icon:'📚', color:'#059669' },
];
