server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

jwt:
  secret: ${JWT_SECRET:n11-talenthub-super-secret-key-minimum-256-bits-hs256-algorithm-dev-only}

management:
  endpoints:
    web:
      exposure:
        include: health
