server:
  port: 8083

spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:n11-talenthub-super-secret-key-minimum-256-bits-hs256-algorithm-dev-only}

management:
  endpoints:
    web:
      exposure:
        include: health
